org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_api_version=0.161.0+26.3

paper_version=26.3.build.49-alpha

shadow_version=9.6.1
run_paper_version=3.1.0

version=1.0
group=me.skaffy
